apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.app_name }}
  labels:
    backstage.io/kubernetes-id: ${{ values.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.app_name }}
  template:
    metadata:
      labels:
        app: ${{ values.app_name }}
        backstage.io/kubernetes-id: ${{ values.app_name }}
    spec:
      containers:
        - name: ${{ values.app_name }}
          image: ghcr.io/backstagessppoc/demo-test-15:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 3000