name: CI-CD-Full-Apply

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set lowercase image name
        run: |
          IMAGE=$(echo "ghcr.io/backstagessppoc/${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push
        run: docker push $IMAGE_NAME:${{ github.sha }}

      - name: Replace Image Tag
        run: |
          sed -i "s|IMAGE_TAG|${{ github.sha }}|g" k8s_manifest/deployment.yaml

      - name: Setup kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Apply
        run: kubectl apply -f k8s_manifest/
