name: CI-CD-Full-Apply

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Service Repo
        uses: actions/checkout@v3
        with:
          path: service

      - name: Set Image Name
        run: |
          IMAGE="ghcr.io/${{ github.repository }}"
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} ./service

      - name: Push Image
        run: docker push $IMAGE_NAME:${{ github.sha }}

      - name: Checkout manifests repo
        uses: actions/checkout@v3
        with:
          repository: BackstageSSPPoC/k8s-manifests
          token: ${{ secrets.GHCR_PAT }}
          path: manifests

      - name: Update Deployment Image
        run: |
          SERVICE=${{ github.event.repository.name }}
          sed -i "s|image:.*|image: $IMAGE_NAME:${{ github.sha }}|g" manifests/apps/$SERVICE/deployment.yaml

      - name: Commit & Push Updated Manifest
        run: |
          cd manifests
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update $SERVICE image to ${{ github.sha }}"
          git push