name: CI-CD-Full-Apply

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Image Name
        run: |
          IMAGE="ghcr.io/${{ github.repository }}"
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Image
        run: docker push $IMAGE_NAME:${{ github.sha }}

      - name: Update Deployment Image Tag
        run: |
          sed -i "s|IMAGE_TAG|${{ github.sha }}|g" k8s_manifest/deployment.yaml

      - name: Commit & Push Updated Manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s_manifest/deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push